### PR TITLE
Feature/ui mockup may05 version

### PR DESCRIPTION
**Pull request by soninob**

### CODE REVIEW

**Comment by edagan** [comment]
@soninob I believe build should be at the project level. Let's talk on Sunday.

**Comment by soninob** [comment]
@edagan - I started doing it at the project level. But then I remembered that you ask me also to support executing multiple projects.
For now, we will keep it in the size of one to reduce additional work on the BE.
Do you think we should keep two implementations to the execution?

**Comment by edagan** [comment]
Project level + multiple calls from UI when more than one project is selected is the way to go, I believe.

**Comment by soninob** [comment]
@edagan - according to our conversation, we will not support multiple projects for now, the route will be under the projectID. no support for building with params for now.
I will update the branch and let you know when done.

**Comment by soninob** [comment]
@edagan - Changes were made based on our conversation.
Let me know if we want to handle actions on the build itself (stopping it, getting it, etc.)

**Comment by edagan** [comment]
Thanks! 
As we discussed, this is the first phase for project-level execution. Merging.

**Comment by rqc** [comment]
@soninob @edagan just reviewing the latest changes for the project level execution API. From what I can see there is no information being sent for the ordering. That would imply that *for now*the backend can decide in which order they are executed. Please confirm :smile: 

Cheers!

**Pull request merged**
